language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"

env:
  global:
    - TEST_DIR=/tmp/test_dir/
    - MODULE=pyrfm

install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose cython scikit-learn
  - conda activate test-environment
  - python setup.py develop

script:
  - mkdir -p $(TEST_DIR)
  - cd $(TEST_DIR)
  - nosetest -v $(MODULE)